apiVersion: v1
kind: Service
metadata:
  name: quacker-account-service
spec:
  type: ClusterIP
  ports:
    - name: 'http-5072'
      port: 5072
      targetPort: 5072
  selector:
    app: quacker-account-service
