apiVersion: v1
kind: Service
metadata:
  name: quacker-quack-service
spec:
  type: ClusterIP
  ports:
    - name: 'http-5000'
      port: 5000
      targetPort: 5000
  selector:
    app: quacker-quack-service
