apiVersion: v1
kind: Service
metadata:
  name: quacker-follow-service
  labels:
    app: quacker-follow-service
    service: quacker-follow-service
spec:
  type: ClusterIP
  ports:
    - name: 'http-5082'
      port: 5082
      targetPort: 5082
  selector:
    app: quacker-follow-service
