// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuackService.Api.Data;

namespace QuackService.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210525183045_AddedTopicsDate")]
    partial class AddedTopicsDate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("QuackService.Api.Models.Mention", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("QuackId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("QuackId");

                    b.ToTable("Mention");
                });

            modelBuilder.Entity("QuackService.Api.Models.Quack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .HasMaxLength(140)
                        .HasColumnType("varchar(140) CHARACTER SET utf8mb4");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Username")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Quacks");
                });

            modelBuilder.Entity("QuackService.Api.Models.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("QuackId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("QuackId");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("QuackService.Api.Models.Mention", b =>
                {
                    b.HasOne("QuackService.Api.Models.Quack", null)
                        .WithMany("Mentions")
                        .HasForeignKey("QuackId");
                });

            modelBuilder.Entity("QuackService.Api.Models.Topic", b =>
                {
                    b.HasOne("QuackService.Api.Models.Quack", null)
                        .WithMany("Topics")
                        .HasForeignKey("QuackId");
                });

            modelBuilder.Entity("QuackService.Api.Models.Quack", b =>
                {
                    b.Navigation("Mentions");

                    b.Navigation("Topics");
                });
#pragma warning restore 612, 618
        }
    }
}
