apiVersion: v1
kind: Service
metadata:
  name: quacker-auth-service
  labels:
    app: quacker-auth-service
    service: quacker-auth-service
spec:
  type: ClusterIP
  ports:
    - name: 'http-5088'
      port: 5088
      targetPort: 5088
  selector:
    app: quacker-auth-service
