apiVersion: apps/v1
kind: Deployment
metadata:
  name: quacker-quack-service
  labels:
    app: quacker-quack-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quacker-quack-service
      version: v1
  template:
    metadata:
      labels:
        app: quacker-quack-service
        version: v1
    spec:
      containers:
        - name: quacker-quack-service
          image: quackernl/quacker-quack-service:latest
          imagePullPolicy: 'Always'
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: '100Mi'
              cpu: '100m'
            limits:
              memory: '200Mi'
              cpu: '500m'
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: quacker-quack-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: quacker-quack-service
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 95
