apiVersion: v1
kind: Service
metadata:
  name: quacker-timeline-service
spec:
  type: ClusterIP
  ports:
    - name: 'http-5067'
      port: 5067
      targetPort: 5067
  selector:
    app: quacker-timeline-service
